language: node_js
node_js:
 - "stable"

cache:
  directories:
    - "node_modules"

install:
  - npm install
script:
  - npm test
after_success:
  - npm run coverage

env:
  global:
  - CODECLIMATE_REPO_TOKEN=9e83697183b61817c399b2199742dc61ed9f1c454e1d973774eafdc8080
